Add initial implementation
gramineproject/device-testing-tools pull request #1
Opened 2022-04-04 06:37 UTC by boryspoplawski

Initial implementation, tested on Ubuntu 22.04 (but should work everywhere, possibly with minimal changes).

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)

2022-04-04 22:19 UTC, mkow reviewed
> Reviewed 1 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 1 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzqdj3QAFkN2rQHyaIf:-Mzqdj3QAFkN2rQHyaIg:bkai6e1) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
> use use 


<!-- Sent from Reviewable.io -->

2022-04-06 11:40 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[gramine_ubuntu22.04.patch, line 18 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyU8us-CLRfW_N82Hs:-MzyU8us-CLRfW_N82Ht:b6lk2qd) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/gramine_ubuntu22.04.patch#L18)):*
> ```Diff
> +-LINKS_DSO_PROGRAM = links-dso-program-c
> +-else
> +-LINKS_DSO_PROGRAM = links-dso-program
> ```

So what's the story behind this `LINKS_DSO_PROGRAM`? Why do you need to remove it? Why is this only applicable to 2.34? Can we move this patch to core Gramine repo?
___
*[README.rst, line 5 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzta6_XAq9NvYoe10Me:-Mzta6_Y7LhW_mBiuROu:b968aiz) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L5)):*
> ```reStructuredText
> *****************************************
> 
> Just a set of tools and scripts designed for testings host device passthrough in
> ```

`testing`
___
*[README.rst, line 13 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyejW73Xe-UiBtK3xS:-MzyejW73Xe-UiBtK3xT:b-p9zfb6) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L13)):*
> ```reStructuredText
> =============
> 
> In order to run Gramine SGX PAL inside QEMU, you need both QEMU and host kernel
> ```

`Gramine SGX PAL` -> `Gramine-SGX`
___
*[README.rst, line 14 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztaHBo5cdLLCFvb4kP:-MztaHBo5cdLLCFvb4kQ:btylzwu) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L14)):*
> ```reStructuredText
> 
> In order to run Gramine SGX PAL inside QEMU, you need both QEMU and host kernel
> to support SGX. The support was added in Linux v5.15 and QEMU v6.2.0
> ```

Please add a dot at the end of the sentence.
___
*[README.rst, line 32 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyevxu4UEqEGkQ2ZnC:-Mzyevxu4UEqEGkQ2ZnD:b-1li191) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L32)):*
> ```reStructuredText
> =================
> 
> TODO: maybe needs a better name
> ```

I'm fine with the current name
___
*[README.rst, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb1yl2vswQquVF2rD:-Mztb1yl2vswQquVF2rE:b3wg3cn) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L34)):*
> ```reStructuredText
> TODO: maybe needs a better name
> 
> Set scripts to build and run the virtual machine. Uses host kernel for
> ```

`Set of scripts`?
___
*[README.rst, line 35 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb9D_7xx37ATxjqzW:-Mztb9D_7xx37ATxjqzX:b-9n7pkq) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L35)):*
> ```reStructuredText
> 
> Set scripts to build and run the virtual machine. Uses host kernel for
> simplicity. Whole (/) host filesystem is mounted readonly at root with
> ```

I'd prefer to have the `/` symbol in double-backticks.
___
*[README.rst, line 36 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbIDNAnCHrQQ-F693:-MztbIDNAnCHrQQ-F694:bbj61q6) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L36)):*
> ```reStructuredText
> Set scripts to build and run the virtual machine. Uses host kernel for
> simplicity. Whole (/) host filesystem is mounted readonly at root with
> a read-write overlay in tmpfs (volatile in memory).
> ```

Why do we need to expose the host filesystem at all? Is it because it's the easiest way to bring Gramine, super-module, etc. inside the VM? Could you please a one-sentence rationale?
___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-Mzyf3AL72CIKxkTizay:b63owex) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
> ```reStructuredText
> a read-write overlay in tmpfs (volatile in memory).
> 
> Super module
> ```

How do you envision this super module to be started inside of the guest VM? I don't see any code that actually enables it.

And in general, how do you envision this repo to be used in our core-gramine CI?
___
*[README.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb_OXB2ANx1sAfW4a:-Mztb_OY5-DrwvZ_Fkjp:bmuazke) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L41)):*
> ```reStructuredText
> ============
> 
> TODO: change name
> ```

I prefer self-describing names. What about `Gramine Device Testing module`?
___
*[README.rst, line 44 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbkujBGvdE8hB0tRy:-MztbkujBGvdE8hB0tRz:bedx8o2) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L44)):*
> ```reStructuredText
> 
> Implemenation of a dummy kernel module, implementing a device which can be
> passed to Gramine to test all required functionality.
> ```

Maybe add `(in particular, shared untrusted memory and ioctl syscall)`.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztbt3F-0I1pqHoNS_J:-Mztbt3F-0I1pqHoNS_K:b-jijjg6) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
> ```reStructuredText
> 
> Currently Gramine (actually glibc 2.34) does not build on Ubuntu 22.04. You may
> use use `gramine_ubuntu22.04.patch` fix that.
> ```

`to fix that`.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbuNb-a_SgLFbhugP:-MztbuNb-a_SgLFbhugQ:b-ga1xt1) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
> ```reStructuredText
> 
> Currently Gramine (actually glibc 2.34) does not build on Ubuntu 22.04. You may
> use use `gramine_ubuntu22.04.patch` fix that.
> ```

What's the story behind it? Shouldn't we update the main Gramine repo then to the Glibc that is supported by Ubuntu 22.04? Or add your patch to the main Gramine repo?
___
*[initramfs_builder/init, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyXb6rEIMjB-CTeiRY:-MzyXb6rEIMjB-CTeiRZ:bu990zv) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/init#L34)):*
> ```
> mount -t tmpfs tmpfs /newroot/tmp
> 
> umount -l /dev
> ```

For my understanding: here you're unmounting the old `/dev` mount, because you already loaded all the `9p` kernel modules and no below commands will use/rely on the old `/dev`? So this is a clean-up purely for sanity?
___
*[initramfs_builder/run.sh, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyaJJd2lR_YJ_JS4rY:-MzyaJJd2lR_YJ_JS4rZ:b-9hgib) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

Why is this file put und [...]

2022-04-06 20:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 7 of 16 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[gramine_ubuntu22.04.patch, line 18 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyU8us-CLRfW_N82Hs:-N--98wGBNzghNXzLEhu:b-hdpfq3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/gramine_ubuntu22.04.patch#L18)):*
> Why do you need to remove it? 

Why? Because it doesn't build (explanation below). Why we can? Because it's used for tests only.

The problem is with building glibc2.34 on systems where the host uses glibc2.35. There was a symbol introduced, which was also versioned for `@2.35` (something with stack unwinding on c++ exceptions). There is this weird c++ program used for who knows what that is only build for tests, which links with nostd but needs that symbol and everything blows up.

> Can we move this patch to core Gramine repo?

We can, but I don't think there is much point - I would expect we move to glibc2.35 soon (IMO we should once ubuntu22.04 is officially released). Once we do, there should be no issues and less patches is better.
___
*[README.rst, line 5 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzta6_XAq9NvYoe10Me:-N--AjbnCoW3glYkE3Cg:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`testing`
</blockquote></details>

Done.
___
*[README.rst, line 13 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyejW73Xe-UiBtK3xS:-N--ApN0Dd5504z07xRA:b-i6l2za) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Gramine SGX PAL` -> `Gramine-SGX`
</blockquote></details>

Is that an official name? I thought we use `SGX PAL`
___
*[README.rst, line 14 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztaHBo5cdLLCFvb4kP:-N--B-Q248IaV_eU5M4B:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end of the sentence.
</blockquote></details>

Done.
___
*[README.rst, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb1yl2vswQquVF2rD:-N--BKuiEA8Ur7Ao1lx9:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Set of scripts`?
</blockquote></details>

Done.
___
*[README.rst, line 35 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb9D_7xx37ATxjqzW:-N--BQdP0ClIZzv-54R4:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer to have the `/` symbol in double-backticks.
</blockquote></details>

Done.
___
*[README.rst, line 36 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbIDNAnCHrQQ-F693:-N--BoPdE8Tk8SWFZ89r:bosvxrg) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need to expose the host filesystem at all? Is it because it's the easiest way to bring Gramine, super-module, etc. inside the VM? Could you please a one-sentence rationale?
</blockquote></details>

Yes, for simplicity. Done.
___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N--KTS10y_GHm7O3Twp:bu9aycr) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
There's a file `new_init`, which just spawns a shell atm. My idea was to used kernel cmdline (so that it's easily changeable in `run.sh` and doesn't require rebuilding anything) to run stuff in two modes:
A) (default) Run some custom testing script, which would go to appropriate directories and run appropriate tests (e.g. LibOS regression)
B) Run shell form manual testing or debugging

Module can be inserted either unconditionally in `new_init` or on that testing script. That part is not yet done, but it's a matter of 2 line bash script, so it should be easy. I wanted to gather the general feedback before + discuss exact details of how we are going to run this in CI (e.g. new pipelines?)

> And in general, how do you envision this repo to be used in our core-gramine CI?

Some details are yet to be discussed, but general idea was to build it (question: where? build once + submit in our packages repo, build everytime on CI or what? I think once is enough, as no changes should be needed for initramfs - only the driver/module would change) and run in dockers as part of some pipelines or create custom ones.
___
*[README.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztb_OXB2ANx1sAfW4a:-N--X4qC80YcG4D74I7g:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I prefer self-describing names. What about `Gramine Device Testing module`?
</blockquote></details>

Done.
___
*[README.rst, line 44 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbkujBGvdE8hB0tRy:-N--MMFyEvncZt7HyNF9:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add `(in particular, shared untrusted memory and ioctl syscall)`.
</blockquote></details>

Done.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzqdj3QAFkN2rQHyaIf:-N--MP4J1NesTl-nWAzP:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> use use 
</blockquote></details>

Done.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mztbt3F-0I1pqHoNS_J:-N--MTEK18eUfsijRyoT:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to fix that`.
</blockquote></details>

Done.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbuNb-a_SgLFbhugP:-N--MVrnButQV7MSPfSA:b-4639za) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the story behind it? Shouldn't we update the main Gramine repo then to the Glibc that is [...]

2022-04-07 01:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 7 of 16 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[README.rst, line 13 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyejW73Xe-UiBtK3xS:-N-0aLoe66mIP2wiGaQZ:bievqb3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is that an official name? I thought we use `SGX PAL`
</blockquote></details>

+1 to Borys
___
*[super-module/Kbuild, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyeFHKDBx0OL_kjWVR:-N-0_uzI7ohb0vbL5hGo:bi1jiej) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/Kbuild#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure. Actually, I think we probably might want to move it out of this repo to another one?
</blockquote></details>

I'd prefer to restrain repos count to the minimum required, it's super PITA to manage submodules / multiple repos in git.
___
*[super-module/main.c, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyc-bWCKANtWobVlkx:-N-0ZtEH3XM7CqTx0eGN:btztkgm) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it's still useful - you can put the cold/unlikely code in some remote location where it won't be prefetched, like ever.
</blockquote></details>

a) I don't think it's really useful, the code will be placed close by anyways, because the compiler doesn't want to emit a long jump. It was more useful with dumb compilers and when x86 branch hints were still recommended.
b) This is test code which doesn't care about grinding performance that much, I'd prefer to keep it as simple and readable as possible.


<!-- Sent from Reviewable.io -->

2022-04-07 07:46 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[gramine_ubuntu22.04.patch, line 18 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyU8us-CLRfW_N82Hs:-N-1vCUO09D7TY093cQ5:bn45ca7) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/gramine_ubuntu22.04.patch#L18)):*
> The problem is with building glibc2.34 on systems where the host uses glibc2.35.

Got it now, this was the missing part. Thanks for the detailed answer!
___
*[README.rst, line 13 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyejW73Xe-UiBtK3xS:-N-1vLsm2KZPp42fSz1e:bezy7hr) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to Borys
</blockquote></details>

Ok, not insisting here. Yeah, we try to avoid Gramine-SGX in official documentation (like, presentations and articles), though I still like/prefer "Gramine-SGX" (well, it was shortened to just "Gramine" for some marketing reasons, whatever). But I thought that having this short description instead of "Gramine with SGX backend" or "Gramine SGX PAL" in *technical* documentation is fine. Anyway, I don't care that much.
___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-1wTGo91_oocL4bTsc:b-qx284b) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
Ok, got it.

> I think once is enough, as no changes should be needed for initramfs...

Agreed, building the initramfs image once, uploading it to our packages.gramineproject.io site, and just downloading in CI scripts sounds reasonable.

> run in dockers as part of some pipelines or create custom ones

From what I remember, spawning a VM inside a Docker container had some hurdles. I think we leaned towards the bare-metall Jenkins job, but maybe I'm confusing with something. Anyway, this is orthogonal to this PR.
___
*[README.rst, line 50 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztbuNb-a_SgLFbhugP:-N-1xCPR6QQEKbGkubPj:b-pbdqz3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

See the other comment. I would just update to glibc from Ubuntu22.04 once it's supported.
</blockquote></details>

Agreed.
___
*[initramfs_builder/run.sh, line 12 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N--Ojzl7cJJVL0bczOG:-N-1yhh2C3ewbi6_0bYR:b-t1cs3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We most likely need some way to change these. Maybe arguments to this shell script (and leave 2 threads, 1G as defaults?)
</blockquote></details>

Let's change this in a separate PR, when the need arises (if at all).
___
*[initramfs_builder/run.sh, line 15 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyVM5W7AXuUIXUm8pI:-N-1yq__36CLmN0jpaBQ:b5jp3t) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L15)):*
>  with device it gets it instantly, without after a significant while, and prints annoying message when it finally does get it

That's an interesting quirk. Well, makes sense.
___
*[qemu/Makefile, line 30 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-1z0tN9yZzxAp3aY-a:-N-1z0tO2Jg_k2xp732A:b-rqhlef) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/403afbe7bfc9e9d724af5b84f0ea5ba8822bc1c4/qemu/Makefile#L30)):*
> ```Makefile
> 	$(MAKE) -C $(QEMU_SRC_DIR)/build
> 	ln -sf $(QEMU_SRC_DIR)/build/qemu-system-x86_64 qemu-system-x86_64
> 	@echo 'QEMU was build successfully. You might want to install it globally now, or add this directory to your $$PATH'
> ```

`was build` -> `was built`

Also, please add a dot at the end
___
*[qemu/patches/fcf-protection.patch, line 10 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MztamrkEyq1_w2loNA-:-N-1zBHp8dip8YYmOlsG:bmxyqkd) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/qemu/patches/fcf-protection.patch#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It won't build without it. This is a bug in new `gcc` or in QEMU buildsystem, hard to decide, there seem to be lot's of discussions about it.

The problem is that these (Intel CET) do not make sense for this target, so they should be disabled, but they are not.
</blockquote></details>

OK, thanks for the explanation.
___
*[super-module/Kbuild, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyeFHKDBx0OL_kjWVR:-N-1xL-3-BnTbJ_8o96h:bhwda9e) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/Kbuild#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to restrain repos count to the minimum required, it's super PITA to manage submodules / multiple repos in git.
</blockquote></details>

Yes, I would also keep the kernel module here. Less repos is better.
___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-1xYZB91rcB-Cn6yUO:b-o16pg3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can't I have a licence named `GPL\x00ish`?
For real: we probably want to change this to something appropriate, but that needs a discussion. It's also unclear to me what to put in here, if we provide code as LGPL3+
</blockquote></details>

Yes, you can :)

But this kernel module is completely separate from the Gramine codebase, why do we care about the LGPL license of core Gramine?
___
*[super-module/main.c, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyc-bWCKANtWobVlkx:-N-1xqs01lzuS-ha-zqv:b-rcdp3l) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

a) I don't think it's really useful, the code will be placed close by anyways, because the compiler doesn't want to emit a long jump. It was more useful with dumb compilers and when x86 branch hints were still recommended.
b) This is test code which doesn't care about grinding performance that much, I'd prefer to keep it as simple and readable as possible.
</blockquote></details>

+1 to Michal, but I won't insist.


<!-- Sent from Reviewable.io -->

2022-04-07 10:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-2GpZ28wHBpX4nUCmw:b-h8299q) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, got it.

> I think once is enough, as no changes should be needed for initramfs...

Agreed, building the initramfs image once, uploading it to our packages.gramineproject.io site, and just downloading in CI scripts sounds reasonable.

> run in dockers as part of some pipelines or create custom ones

From what I remember, spawning a VM inside a Docker container had some hurdles. I think we leaned towards the bare-metall Jenkins job, but maybe I'm confusing with something. Anyway, this is orthogonal to this PR.
</blockquote></details>

I think is somewhat important as it might affect the design of these tools. After all their job is to be run both in CI and manually.
___
*[qemu/Makefile, line 30 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-1z0tN9yZzxAp3aY-a:-N-2_ydECDVzDtvWaOQK:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/403afbe7bfc9e9d724af5b84f0ea5ba8822bc1c4/qemu/Makefile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`was build` -> `was built`

Also, please add a dot at the end
</blockquote></details>

Done.
___
*[super-module/Kbuild, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyeFHKDBx0OL_kjWVR:-N-2H56Z42fMVWl5Tyc9:b97z79u) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/Kbuild#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I would also keep the kernel module here. Less repos is better.
</blockquote></details>

All right.
Although I would like to point that we wouldn't ever use submodules and moving this to another repo won't increase the amount of repos we would use in CI (because initramfs will be build once and just downloaded - only the driver will be built everytime, which is why I wanted to move it).
___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-2HUwC5fVjCzFKFeT3:byzh2yo) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, you can :)

But this kernel module is completely separate from the Gramine codebase, why do we care about the LGPL license of core Gramine?
</blockquote></details>

I guess we do not, still we need to pick some license (whatever that would be) and I'm in no position to picking that myself. Something to discuss on next meeting, or would it be enough if couple of maintainers just agreed here?
___
*[super-module/main.c, line 34 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyc-bWCKANtWobVlkx:-N-2IdBl78dzeyA0P-zH:bk1yn5e) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L34)):*
a)
> the code will be placed close by anyways, because the compiler doesn't want to emit a long jump. 

Not really, compilers prefer long jumps over unnecessary jumps.

>  It was more useful with dumb compilers 

Sure it was. Doesn't mean it does nothing.

The code will be different. How much of a performance gain will that give? No idea. Maybe a lot. Maybe nothing. I'm not an expert on these matters.

b)
This is a valid point and I'll remove them then.


<!-- Sent from Reviewable.io -->

2022-04-08 07:10 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-6swt52L514HoUd8OV:b-xglgwc) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think is somewhat important as it might affect the design of these tools. After all their job is to be run both in CI and manually.
</blockquote></details>

@woju Could you help us here? We need to decide whether we will use on the following in our Jenkins CI:
1. Docker container job (as we do now), that spawns a VM using QEMU/KVM
2. Bare-metal job, that spawns a VM using QEMU/KVM

In both cases, this job has requirements:
- Host Linux must be 5.15 or higher (available in Ubuntu 22.04)

It's definitely possible to spawn a VM from within a Docker container, and it looks pretty trivial to enable this (looking at https://medium.com/axon-technologies/installing-a-windows-virtual-machine-in-a-linux-docker-container-c78e4c3f9ba1).

So I guess the only question is: how much overhead/cumbersome will it be to maintain a "VM-inside-Docker" scenario in our Jenkins?
___
*[initramfs_builder/run.sh, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyaJJd2lR_YJ_JS4rY:-N-7-Sl8ByrIzcxfJnql:b-gda4ce) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, most likely. It was easier to test it this way. I'll leave it this way, until we decide on exact procedure of using this in CI.
</blockquote></details>

Ok. Please unblock yourself on this comment.
___
*[super-module/Kbuild, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyeFHKDBx0OL_kjWVR:-N-6zyAlCHO_VCpajHFq:b-ia6uhg) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/Kbuild#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right.
Although I would like to point that we wouldn't ever use submodules and moving this to another repo won't increase the amount of repos we would use in CI (because initramfs will be build once and just downloaded - only the driver will be built everytime, which is why I wanted to move it).
</blockquote></details>

Yes, but we'll still have one more repo to maintain (like, I periodically forget that we have `examples` repo, and this one I will forget for sure). I don't think it's worth it.
___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-7-BdP5YpWuz4398-I:bh3vc2y) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess we do not, still we need to pick some license (whatever that would be) and I'm in no position to picking that myself. Something to discuss on next meeting, or would it be enough if couple of maintainers just agreed here?
</blockquote></details>

That's just a tiny kernel module used purely for testing purposes. Let's wait for @mkow's reply, but I don't think we care much about the specific license.


<!-- Sent from Reviewable.io -->

2022-04-08 08:11 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-7CBqD0Hg89xW4m57t:beidrbq) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could you help us here? We need to decide whether we will use on the following in our Jenkins CI:
1. Docker container job (as we do now), that spawns a VM using QEMU/KVM
2. Bare-metal job, that spawns a VM using QEMU/KVM

In both cases, this job has requirements:
- Host Linux must be 5.15 or higher (available in Ubuntu 22.04)

It's definitely possible to spawn a VM from within a Docker container, and it looks pretty trivial to enable this (looking at https://medium.com/axon-technologies/installing-a-windows-virtual-machine-in-a-linux-docker-container-c78e4c3f9ba1).

So I guess the only question is: how much overhead/cumbersome will it be to maintain a "VM-inside-Docker" scenario in our Jenkins?
</blockquote></details>

I created this with 1) in mind. Current setup passes whole host filesystem to VM (albeit readonly). The idea was that we build Gramine in docker (just as we do now) and just pass the whole docker fs to VM. This is definitely possible and we actually don't have to do much (well, we need to expose /dev/kvm inside docker).
And yes, the only requirement is that host kernel is at least v5.15, as you pointed out.
I think the easiest way would be to just move ubuntu18.04 to 22.04 once it's released and augment these pipelines with device-in-VM tests.

wdyt
@dimakuv @mkow @woju 
___
*[initramfs_builder/run.sh, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyaJJd2lR_YJ_JS4rY:-N-7DaRa7WB99bQcWOFl:b-re0ao7) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok. Please unblock yourself on this comment.
</blockquote></details>

Why? We've not yet decided what to do
___
*[super-module/Kbuild, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyeFHKDBx0OL_kjWVR:-N-7D8RZ4h7hgnMifI0d:b-jgv2o2) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/Kbuild#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, but we'll still have one more repo to maintain (like, I periodically forget that we have `examples` repo, and this one I will forget for sure). I don't think it's worth it.
</blockquote></details>

Not really one more - in both cases you get only one repo to maintain (this vs pure module) as hopefully initramfs can be built once per year or something.
I don't mind sticking to what we have now, just pointing out :)


<!-- Sent from Reviewable.io -->

2022-04-08 10:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-7jU5pDWxnQA6p1ich:b-i8a53g) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I created this with 1) in mind. Current setup passes whole host filesystem to VM (albeit readonly). The idea was that we build Gramine in docker (just as we do now) and just pass the whole docker fs to VM. This is definitely possible and we actually don't have to do much (well, we need to expose /dev/kvm inside docker).
And yes, the only requirement is that host kernel is at least v5.15, as you pointed out.
I think the easiest way would be to just move ubuntu18.04 to 22.04 once it's released and augment these pipelines with device-in-VM tests.

wdyt
@dimakuv @mkow @woju 
</blockquote></details>

+1 do the first option
___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-7hPa818RISbzBM55w:bkr4r18) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's just a tiny kernel module used purely for testing purposes. Let's wait for @mkow's reply, but I don't think we care much about the specific license.
</blockquote></details>

I think just using GPLv2 is fine here. We don't ship this anywhere anyways.


<!-- Sent from Reviewable.io -->

2022-04-08 11:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-7yYK1-HD14EzJKeHg:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think just using GPLv2 is fine here. We don't ship this anywhere anyways.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 14:53 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 15 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-8ZjBT5sphEb3sURTx:b-156uqq) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 do the first option
</blockquote></details>

I prefer first option in case we were to move CI to some "modern CI framework", and many of those strongly favour running things in container or containers. To answer a question, right now 1) is not more cumbersome than 2) and in the future it's likely 2) would be worse than 1).
___
*[super-module/main.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzybRMI7V-ekIHqMN6x:-N-8_ewZ9dzOCXG2ZFOf:b-ouhq7j) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/super-module/main.c#L16)):*
> Is this legal to write license like this?

Oh, man. People do it for like 20 years: https://lwn.net/Articles/82305/, and it's because they know it's illegal. :)


<!-- Sent from Reviewable.io -->

2022-04-11 07:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[README.rst, line 38 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-Mzyf3AL72CIKxkTizax:-N-M_x1e9EOnc3bm_pz1:buhsnmu) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/README.rst#L38)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I prefer first option in case we were to move CI to some "modern CI framework", and many of those strongly favour running things in container or containers. To answer a question, right now 1) is not more cumbersome than 2) and in the future it's likely 2) would be worse than 1).
</blockquote></details>

Thanks everyone. Then this is settled -- we go for option 1 ("VM-inside-Docker").
___
*[initramfs_builder/run.sh, line 1 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-MzyaJJd2lR_YJ_JS4rY:-N-MadtNBNBO9y98fKV1:bhut7vg) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/5289962b8890cd183aa620bb3b9821d4604a2de5/initramfs_builder/run.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why? We've not yet decided what to do
</blockquote></details>

I thought we're postponing this until some follow-up PRs. We already decided to run VM-inside-Docker, and where to put this file doesn't seem important right now. I don't mind keeping this file under this dir.


<!-- Sent from Reviewable.io -->

2022-04-14 09:38 UTC, dimakuv commented
For historical reference. I tested this on a machine with Ubuntu 20.04 and Linux 5.18.

## Install QEMU 6.2.0

Ubuntu 20.04 has an old version of QEMU, so I used the `qemu/Makefile` to build and locally install it. I had to install the following dependencies in order to build QEMU:
```
apt update -y
apt install ninja-build pkgconf libgtk2.0-dev libcap-ng-dev libattr1-dev
```

TO BE CONTINUED

2022-04-14 09:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-bRFS11kCotaCO1geA:baoagy5) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
> ```Makefile
> 	kernel/fs/fscache/fscache.ko \
> 	kernel/fs/netfs/netfs.ko \
> 	kernel/fs/overlayfs/overlay.ko
> ```

@boryspoplawski My stock Ubuntu 20.04 (with Linux 5.18) doesn't have several of these modules. In particular:
- `kernel/net/9p/9pnet_virtio.ko`
- `kernel/net/9p/9pnet.ko`
-  `kernel/fs/9p/9p.ko`
-  `kernel/fs/netfs/netfs.ko`

I can't figure out how to install these kernel modules. How did you do that?


<!-- Sent from Reviewable.io -->

2022-04-14 09:48 UTC, boryspoplawski reviewed
I think I installed `libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev bzip2 ninja-build python3 libcap-ng-dev libattr1-dev`

> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-:-N-bSZXl9FG_xK4z1HyM:b9xxw4p)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-bT-kbBtZO7UYAGQNI:brb69th) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski My stock Ubuntu 20.04 (with Linux 5.18) doesn't have several of these modules. In particular:
- `kernel/net/9p/9pnet_virtio.ko`
- `kernel/net/9p/9pnet.ko`
-  `kernel/fs/9p/9p.ko`
-  `kernel/fs/netfs/netfs.ko`

I can't figure out how to install these kernel modules. How did you do that?
</blockquote></details>

`kernel/fs/netfs/netfs.ko` this one was introduced in never kenrels, I believe, so it's expected. For the rest of above I have no idea, they should be there. You had others you did not list?


<!-- Sent from Reviewable.io -->

2022-04-14 10:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-bWbBL3yt-WBtuq5t5:b-rfq15j) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
> You had others you did not list?

Yes, the other ones in your list are there. In particular, `kernel/fs/fscache/fscache.ko` and `kernel/fs/overlayfs/overlay.ko` are there.


<!-- Sent from Reviewable.io -->

2022-04-14 10:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 14 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-beike4r3BWEMPgFLr:b1l530f) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> You had others you did not list?

Yes, the other ones in your list are there. In particular, `kernel/fs/fscache/fscache.ko` and `kernel/fs/overlayfs/overlay.ko` are there.
</blockquote></details>

Try the new version


<!-- Sent from Reviewable.io -->

2022-04-14 14:16 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-cQQBy0KN-EqUrXgzy:b-zeni9c) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Try the new version
</blockquote></details>

It works, though there are these warnings:
```
insmod: can't insert '/modules/9pnet.ko': File exists
qemu-system-x86_64: warning: 9p: Multiple devices detected in same VirtFS export, which might lead to file ID collisions and
```

The auto-generated `insert_modules.sh` looks like this (on my Ubuntu 22.04 beta with Linux 5.17):
```
insmod /lib/modules/5.17.3-051703-generic/kernel/fs/netfs/netfs.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/fs/fscache/fscache.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/net/9p/9pnet.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/fs/9p/9p.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/net/9p/9pnet.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/net/9p/9pnet_virtio.ko
insmod /lib/modules/5.17.3-051703-generic/kernel/fs/overlayfs/overlay.ko
```


<!-- Sent from Reviewable.io -->

2022-04-14 15:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-cbX_00BJgdVLcL4si:b-hw8zl3) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Do you think these warnings are something we care about, or we can ignore them?

If we can ignore them, I would like to merge this PR.
</blockquote></details>

First one is due to inserting the same module twice - it's a dependency for two others, so it's twice on that list. Since we are using make+bash,  getting rid of duplicates is not trivial (we cannot simply sort the list, because we need to preserve the order of inserts). Since this is harmless, I would just leave it as it is. (maybe just add a comment explaining this)

The other warning is, I think but I'm not sure, because host FS contains devices in /dev which we passthrough via 9p virtio. We never use them and we immediately shadow `/dev` with our own, so this shouldn't be an issue.


<!-- Sent from Reviewable.io -->

2022-04-14 15:14 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-ccvZc4PfoEC39AnTa:b-usedsm) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

First one is due to inserting the same module twice - it's a dependency for two others, so it's twice on that list. Since we are using make+bash,  getting rid of duplicates is not trivial (we cannot simply sort the list, because we need to preserve the order of inserts). Since this is harmless, I would just leave it as it is. (maybe just add a comment explaining this)

The other warning is, I think but I'm not sure, because host FS contains devices in /dev which we passthrough via 9p virtio. We never use them and we immediately shadow `/dev` with our own, so this shouldn't be an issue.
</blockquote></details>

Please add a comment then, and we're done with this PR


<!-- Sent from Reviewable.io -->

2022-04-14 15:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: 15 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[initramfs_builder/Makefile, line 49 at r4](https://reviewable.io/reviews/gramineproject/device-testing-tools/1#-N-bRFS11kCotaCO1ge9:-N-cecTyCn6Yd1Myi-RN:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/2394cb0e401c51e6b8f871b9941adfc486334d76/initramfs_builder/Makefile#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment then, and we're done with this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 15:32 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-14 15:33 UTC, merged