Add `GRAMINE_TEST_DEV_IOCTL_GET_SET_SIZE` ioctl to the Gramine test device
gramineproject/device-testing-tools pull request #9
Opened 2023-08-01 11:52 UTC by dimakuv

This ioctl can be used to test the `onlyif` keyword of Gramine ioctl manifest syntax.

2023-08-11 15:18 UTC, donporter approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`gramine-device-testing-module/main.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nb_9jvTAY-s67vnH2xu:-Nb_9jvTAY-s67vnH2xv:byubwfs) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/90ce9ceb159d7dc71b2ad9e6585b6b9fefd9e13b/gramine-device-testing-module/main.c#L223)):*
> ```C
>                 if (arg.size != 0) {
>                     /* currently can only set the size to zero (i.e. clear the buffer) */
>                     return -EINVAL;
> ```

Consider adding a warning/log message here, since this behavior isn't intuitive/obvious.
___
*[`gramine-device-testing-module/main.c` line 225 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nb_9v6mA-GBMqK8o9FU:-Nb_9v6mA-GBMqK8o9FV:b-n6fek1) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/90ce9ceb159d7dc71b2ad9e6585b6b9fefd9e13b/gramine-device-testing-module/main.c#L225)):*
> ```C
>                     return -EINVAL;
>                 }
>                 kfree(data->buf);
> ```

Should you check if data->buf is NULL?  I believe kfree will tolerate this, but could indicate a problem.


<!-- Sent from Reviewable.io -->

2023-08-21 06:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter)

___
*[`gramine-device-testing-module/main.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nb_9jvTAY-s67vnH2xu:-NcLndL33ch-AHYo7z6H:bb6un1j) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/90ce9ceb159d7dc71b2ad9e6585b6b9fefd9e13b/gramine-device-testing-module/main.c#L223)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider adding a warning/log message here, since this behavior isn't intuitive/obvious.
</blockquote></details>

Done
___
*[`gramine-device-testing-module/main.c` line 225 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nb_9v6mA-GBMqK8o9FU:-NcLmrKSDvWTq9noTLIn:b-3vhgp4) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/90ce9ceb159d7dc71b2ad9e6585b6b9fefd9e13b/gramine-device-testing-module/main.c#L225)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Should you check if data->buf is NULL?  I believe kfree will tolerate this, but could indicate a problem.
</blockquote></details>

I don't see a need for this, and from what I know, Linux community doesn't write code like
```
if (buf)
    kfree(buf)
```

So I prefer to keep my code as is, unless there is a strong reason to change it.


<!-- Sent from Reviewable.io -->

2023-08-23 14:10 UTC, donporter submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-24 00:53 UTC, mkow requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 47 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nc_07hqEW_A5DrUzm8Z:-Nc_07hqEW_A5DrUzm8_:b-h8lfa2) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/f9bd537b03ee60aa6fc16b8e3f57d2537cc57339/gramine-device-testing-module/gramine_test_dev_ioctl.h#L47)):*
> ```objc
> struct gramine_test_dev_ioctl_get_set_size {
>     char do_set; /* 1 means set the size, 0 means get the size */
>     char pad[7];
> ```

I'd prefer `uint8_t` here and above.


<!-- Sent from Reviewable.io -->

2023-08-24 04:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 47 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/9#-Nc_07hqEW_A5DrUzm8Z:-Nc_l-_V9BjUbUJZdl0f:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/f9bd537b03ee60aa6fc16b8e3f57d2537cc57339/gramine-device-testing-module/gramine_test_dev_ioctl.h#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `uint8_t` here and above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 14:30 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-24 14:35 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/9)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-24 14:36 UTC, merged